# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' hungarian_cc
#' @param cost cost matrix
hungarian_cc <- function(cost) {
    .Call('_hexmapr_hungarian_cc', PACKAGE = 'hexmapr', cost)
}

#' hungariansafe_cc
#' @param cost cost matrix
hungariansafe_cc <- function(cost) {
    .Call('_hexmapr_hungariansafe_cc', PACKAGE = 'hexmapr', cost)
}

